"""Create the first production-ready DayForge schema.

Revision ID: 000000000001
Revises:
Create Date: 2026-09-11

All databases created before this baseline contained development data only and
must be reset instead of stamped or upgraded into this revision.
"""

from uuid import uuid4
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "000000000001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_uuid", sa.String(length=36), nullable=False),
        sa.Column("sync_epoch", sa.String(length=36), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_uuid"),
        sa.UniqueConstraint("sync_epoch"),
    )
    op.execute(
        sa.text(
            "INSERT INTO server_instances(id, instance_uuid, sync_epoch, protocol_version, created_at) "
            "VALUES (1, :instance_uuid, :sync_epoch, 4, CURRENT_TIMESTAMP)"
        ).bindparams(instance_uuid=str(uuid4()), sync_epoch=str(uuid4()))
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(op.f("ix_users_public_id"), "users", ["public_id"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(length=11), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_tokens_token_hash"), "api_tokens", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "client_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("installation_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("app_version", sa.String(length=50), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("device_class", sa.String(length=20), nullable=False),
        sa.Column("structural_edit_enabled", sa.Boolean(), nullable=False),
        sa.Column("capability_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "device_class IN ('interactive','hardware','automation')",
            name="ck_client_device_class",
        ),
        sa.CheckConstraint(
            "platform IN ('android','ios','desktop','hardware','service')",
            name="ck_client_device_platform",
        ),
        sa.CheckConstraint(
            "capability_revision >= 1", name="ck_client_device_capability_revision"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id", name="uq_client_devices_public_id"),
        sa.UniqueConstraint(
            "user_id", "installation_id", name="uq_client_device_installation"
        ),
    )
    op.create_index(
        op.f("ix_client_devices_device_class"),
        "client_devices",
        ["device_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_devices_installation_id"),
        "client_devices",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_devices_public_id"),
        "client_devices",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_devices_revoked_at"),
        "client_devices",
        ["revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_devices_user_id"), "client_devices", ["user_id"], unique=False
    )
    op.create_table(
        "households",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id", name="uq_households_public_id"),
    )
    op.create_index(
        op.f("ix_households_created_by_user_id"),
        "households",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_households_deleted_at"), "households", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_households_public_id"), "households", ["public_id"], unique=False
    )
    op.create_table(
        "plan_nodes",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.Column("node_kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column("color_hex", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "node_kind IN ('goal','activity')", name="ck_plan_node_kind"
        ),
        sa.CheckConstraint(
            "status IN ('active','paused','completed','failed','archived')",
            name="ck_plan_node_status",
        ),
        sa.CheckConstraint(
            "parent_node_id IS NULL OR parent_node_id != id",
            name="ck_plan_node_not_self_parent",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_node_id"],
            ["plan_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_plan_node_owner_public_id"
        ),
    )
    op.create_index(
        op.f("ix_plan_nodes_created_by_user_id"),
        "plan_nodes",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_nodes_deleted_at"), "plan_nodes", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_plan_nodes_node_kind"), "plan_nodes", ["node_kind"], unique=False
    )
    op.create_index(
        op.f("ix_plan_nodes_owner_user_id"),
        "plan_nodes",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_nodes_parent_node_id"),
        "plan_nodes",
        ["parent_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plan_nodes_public_id"), "plan_nodes", ["public_id"], unique=False
    )
    op.create_index(
        op.f("ix_plan_nodes_status"), "plan_nodes", ["status"], unique=False
    )
    op.create_table(
        "tracked_metrics",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.Column("aggregation_type", sa.String(length=30), nullable=False),
        sa.Column("target_direction", sa.String(length=30), nullable=True),
        sa.Column("target_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column(
            "target_value_upper", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column("color_hex", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "decimal_places BETWEEN 0 AND 6", name="ck_tracked_metric_decimal_places"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_tracked_metric_owner_public_id"
        ),
    )
    op.create_index(
        op.f("ix_tracked_metrics_created_by_user_id"),
        "tracked_metrics",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_metrics_deleted_at"),
        "tracked_metrics",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_metrics_owner_user_id"),
        "tracked_metrics",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_metrics_public_id"),
        "tracked_metrics",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_metrics_status"), "tracked_metrics", ["status"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_profiles_user"),
    )
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "activity_details",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("tracking_mode", sa.String(length=20), nullable=False),
        sa.Column("is_countdown", sa.Boolean(), nullable=False),
        sa.Column("recurrence_rule_json", sa.String(), nullable=False),
        sa.Column("completion_policy", sa.String(length=20), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("target_unit", sa.String(length=50), nullable=True),
        sa.Column("target_cycles", sa.Integer(), nullable=True),
        sa.Column("failure_policy_json", sa.String(), nullable=False),
        sa.Column("preferred_local_time", sa.Time(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("origin_assignment_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "completion_policy IN ('recurring','one_and_done')",
            name="ck_activity_completion_policy",
        ),
        sa.CheckConstraint(
            "tracking_mode IN ('check','count','duration')",
            name="ck_activity_tracking_mode",
        ),
        sa.CheckConstraint(
            "target_cycles IS NULL OR target_cycles > 0",
            name="ck_activity_target_cycles",
        ),
        sa.CheckConstraint("target_value >= 0", name="ck_activity_target_value"),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["plan_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_index(
        op.f("ix_activity_details_origin_assignment_id"),
        "activity_details",
        ["origin_assignment_id"],
        unique=False,
    )
    op.create_table(
        "entity_revision_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_uuid", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("origin_device_id", sa.Integer(), nullable=True),
        sa.Column("origin_operation_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "operation IN ('upsert','delete')",
            name="ck_entity_revision_snapshot_operation",
        ),
        sa.CheckConstraint(
            "revision >= 1", name="ck_entity_revision_snapshot_revision"
        ),
        sa.ForeignKeyConstraint(
            ["origin_device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id",
            "entity_type",
            "entity_uuid",
            "revision",
            name="uq_entity_revision_snapshot",
        ),
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_created_at"),
        "entity_revision_snapshots",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_entity_type"),
        "entity_revision_snapshots",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_entity_uuid"),
        "entity_revision_snapshots",
        ["entity_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_origin_device_id"),
        "entity_revision_snapshots",
        ["origin_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_origin_operation_id"),
        "entity_revision_snapshots",
        ["origin_operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_revision_snapshots_owner_user_id"),
        "entity_revision_snapshots",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "goal_details",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("target_cycles", sa.Integer(), nullable=True),
        sa.Column("failure_policy_json", sa.String(), nullable=False),
        sa.Column("evaluation_policy_json", sa.String(), nullable=False),
        sa.Column("manual_result", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["plan_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_table(
        "household_memberships",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner','admin','member')", name="ck_household_membership_role"
        ),
        sa.CheckConstraint(
            "status IN ('invited','active','left','removed')",
            name="ck_household_membership_status",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "household_id", "user_id", name="uq_household_membership_user"
        ),
        sa.UniqueConstraint("public_id", name="uq_household_memberships_public_id"),
    )
    op.create_index(
        op.f("ix_household_memberships_deleted_at"),
        "household_memberships",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_household_memberships_household_id"),
        "household_memberships",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_household_memberships_public_id"),
        "household_memberships",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_household_memberships_user_id"),
        "household_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "metric_observations",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_device_public_id", sa.String(length=36), nullable=True),
        sa.Column("external_event_id", sa.String(length=200), nullable=True),
        sa.Column("recorded_by_user_id", sa.Integer(), nullable=True),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["tracked_metrics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_metric_observation_owner_public_id"
        ),
        sa.UniqueConstraint(
            "source_device_public_id",
            "external_event_id",
            name="uq_metric_observation_external_source",
        ),
    )
    op.create_index(
        op.f("ix_metric_observations_deleted_at"),
        "metric_observations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_local_date"),
        "metric_observations",
        ["local_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_metric_id"),
        "metric_observations",
        ["metric_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_occurred_at"),
        "metric_observations",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_owner_user_id"),
        "metric_observations",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_public_id"),
        "metric_observations",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_recorded_by_user_id"),
        "metric_observations",
        ["recorded_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_source_device_public_id"),
        "metric_observations",
        ["source_device_public_id"],
        unique=False,
    )
    op.create_table(
        "sync_changes",
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_uuid", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("origin_user_id", sa.Integer(), nullable=False),
        sa.Column("origin_device_id", sa.Integer(), nullable=True),
        sa.Column("origin_operation_id", sa.String(length=36), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_sync_changes_changed_at"), "sync_changes", ["changed_at"], unique=False
    )
    op.create_index(
        op.f("ix_sync_changes_entity_type"),
        "sync_changes",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_changes_entity_uuid"),
        "sync_changes",
        ["entity_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_changes_origin_device_id"),
        "sync_changes",
        ["origin_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_changes_origin_operation_id"),
        "sync_changes",
        ["origin_operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_changes_origin_user_id"),
        "sync_changes",
        ["origin_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_sync_changes_recipient_sequence",
        "sync_changes",
        ["recipient_user_id", "sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_changes_recipient_user_id"),
        "sync_changes",
        ["recipient_user_id"],
        unique=False,
    )
    op.create_table(
        "sync_cursors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("last_pulled_sequence", sa.Integer(), nullable=False),
        sa.Column("last_pull_at", sa.DateTime(), nullable=True),
        sa.Column("last_push_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id", name="uq_sync_cursor_user_device"),
    )
    op.create_index(
        op.f("ix_sync_cursors_device_id"), "sync_cursors", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_sync_cursors_user_id"), "sync_cursors", ["user_id"], unique=False
    )
    op.create_table(
        "sync_operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_uuid", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=True),
        sa.Column("result_json", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id", "operation_id", name="uq_sync_operation_device_operation"
        ),
    )
    op.create_index(
        op.f("ix_sync_operations_device_id"),
        "sync_operations",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operations_entity_uuid"),
        "sync_operations",
        ["entity_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operations_operation_id"),
        "sync_operations",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operations_status"), "sync_operations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sync_operations_user_id"), "sync_operations", ["user_id"], unique=False
    )
    op.create_table(
        "timer_commands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("session_public_id", sa.String(length=36), nullable=False),
        sa.Column("command_sequence", sa.Integer(), nullable=False),
        sa.Column("command_type", sa.String(length=20), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_json", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "command_type IN ('start','pause','resume','stop','cancel','takeover')",
            name="ck_timer_command_type",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id", "command_id", name="uq_timer_command_device_command"
        ),
    )
    op.create_index(
        op.f("ix_timer_commands_command_id"),
        "timer_commands",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_commands_command_sequence"),
        "timer_commands",
        ["command_sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_commands_device_id"),
        "timer_commands",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_commands_session_public_id"),
        "timer_commands",
        ["session_public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_commands_status"), "timer_commands", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_timer_commands_user_id"), "timer_commands", ["user_id"], unique=False
    )
    op.create_table(
        "user_sync_policies",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("primary_editor_device_id", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("revision >= 1", name="ck_user_sync_policy_revision"),
        sa.ForeignKeyConstraint(
            ["primary_editor_device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_sync_policies_primary_editor_device_id"),
        "user_sync_policies",
        ["primary_editor_device_id"],
        unique=False,
    )
    op.create_table(
        "activity_events",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("activity_node_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("duration_milliseconds", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_device_public_id", sa.String(length=36), nullable=True),
        sa.Column("external_event_id", sa.String(length=200), nullable=True),
        sa.Column("recorded_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reverts_event_id", sa.Integer(), nullable=True),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('check_in','count_delta','count_snapshot','duration_session','revert')",
            name="ck_activity_event_type",
        ),
        sa.CheckConstraint(
            "duration_milliseconds IS NULL OR duration_milliseconds >= 0",
            name="ck_activity_event_duration_ms",
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name="ck_activity_event_duration",
        ),
        sa.ForeignKeyConstraint(
            ["activity_node_id"],
            ["activity_details.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reverts_event_id"],
            ["activity_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_activity_event_owner_public_id"
        ),
        sa.UniqueConstraint(
            "source_device_public_id",
            "external_event_id",
            name="uq_activity_event_external_source",
        ),
    )
    op.create_index(
        op.f("ix_activity_events_activity_node_id"),
        "activity_events",
        ["activity_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_deleted_at"),
        "activity_events",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_event_type"),
        "activity_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_local_date"),
        "activity_events",
        ["local_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_occurred_at"),
        "activity_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_owner_user_id"),
        "activity_events",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_public_id"),
        "activity_events",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_recorded_by_user_id"),
        "activity_events",
        ["recorded_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_reverts_event_id"),
        "activity_events",
        ["reverts_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_events_source_device_public_id"),
        "activity_events",
        ["source_device_public_id"],
        unique=False,
    )
    op.create_index(
        "uq_activity_event_revert_target",
        "activity_events",
        ["reverts_event_id"],
        unique=True,
        sqlite_where=sa.text("reverts_event_id IS NOT NULL"),
        postgresql_where=sa.text("reverts_event_id IS NOT NULL"),
    )
    op.create_table(
        "activity_metric_links_v2",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("activity_node_id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("coefficient", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("show_in_activity_detail", sa.Boolean(), nullable=False),
        sa.Column("prompt_on_complete", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_node_id"],
            ["activity_details.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["tracked_metrics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_activity_metric_link_owner_public_id"
        ),
    )
    op.create_index(
        op.f("ix_activity_metric_links_v2_activity_node_id"),
        "activity_metric_links_v2",
        ["activity_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_metric_links_v2_deleted_at"),
        "activity_metric_links_v2",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_metric_links_v2_metric_id"),
        "activity_metric_links_v2",
        ["metric_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_metric_links_v2_owner_user_id"),
        "activity_metric_links_v2",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_metric_links_v2_public_id"),
        "activity_metric_links_v2",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        "uq_activity_metric_link_active_pair",
        "activity_metric_links_v2",
        ["activity_node_id", "metric_id"],
        unique=True,
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "duration_day_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_event_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint("duration_ms > 0", name="ck_duration_allocation_positive"),
        sa.ForeignKeyConstraint(
            ["activity_event_id"],
            ["activity_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "activity_event_id", "local_date", name="uq_duration_allocation_event_date"
        ),
    )
    op.create_index(
        op.f("ix_duration_day_allocations_activity_event_id"),
        "duration_day_allocations",
        ["activity_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duration_day_allocations_local_date"),
        "duration_day_allocations",
        ["local_date"],
        unique=False,
    )
    op.create_table(
        "timer_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("activity_node_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("controller_device_id", sa.Integer(), nullable=False),
        sa.Column("control_generation", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("next_command_sequence", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("state_changed_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_countdown", sa.Boolean(), nullable=False),
        sa.Column("target_seconds", sa.Integer(), nullable=False),
        sa.Column("max_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("active_elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("completed_event_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "state IN ('running','paused','completed','cancelled')",
            name="ck_timer_session_state",
        ),
        sa.CheckConstraint("active_elapsed_ms >= 0", name="ck_timer_session_elapsed"),
        sa.CheckConstraint(
            "control_generation >= 1", name="ck_timer_session_generation"
        ),
        sa.CheckConstraint(
            "max_duration_seconds > 0", name="ck_timer_session_max_duration"
        ),
        sa.CheckConstraint(
            "next_command_sequence >= 2", name="ck_timer_session_next_sequence"
        ),
        sa.CheckConstraint("revision >= 1", name="ck_timer_session_revision"),
        sa.ForeignKeyConstraint(
            ["activity_node_id"],
            ["activity_details.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_event_id"],
            ["activity_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["controller_device_id"],
            ["client_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "public_id", name="uq_timer_session_owner_public_id"
        ),
    )
    op.create_index(
        op.f("ix_timer_sessions_activity_node_id"),
        "timer_sessions",
        ["activity_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_sessions_completed_event_id"),
        "timer_sessions",
        ["completed_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_sessions_controller_device_id"),
        "timer_sessions",
        ["controller_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_sessions_owner_user_id"),
        "timer_sessions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_sessions_public_id"),
        "timer_sessions",
        ["public_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timer_sessions_state"), "timer_sessions", ["state"], unique=False
    )
    op.create_index(
        "uq_timer_session_owner_active",
        "timer_sessions",
        ["owner_user_id"],
        unique=True,
        sqlite_where=sa.text("state IN ('running','paused')"),
        postgresql_where=sa.text("state IN ('running','paused')"),
    )
    op.create_table(
        "timer_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="ck_timer_segment_duration"
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_timer_segment_sequence"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["timer_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "sequence", name="uq_timer_segment_session_sequence"
        ),
    )
    op.create_index(
        op.f("ix_timer_segments_session_id"),
        "timer_segments",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "uq_timer_segment_session_open",
        "timer_segments",
        ["session_id"],
        unique=True,
        sqlite_where=sa.text("ended_at IS NULL"),
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_timer_segment_session_open",
        table_name="timer_segments",
        sqlite_where=sa.text("ended_at IS NULL"),
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_timer_segments_session_id"), table_name="timer_segments")
    op.drop_table("timer_segments")
    op.drop_index(
        "uq_timer_session_owner_active",
        table_name="timer_sessions",
        sqlite_where=sa.text("state IN ('running','paused')"),
        postgresql_where=sa.text("state IN ('running','paused')"),
    )
    op.drop_index(op.f("ix_timer_sessions_state"), table_name="timer_sessions")
    op.drop_index(op.f("ix_timer_sessions_public_id"), table_name="timer_sessions")
    op.drop_index(op.f("ix_timer_sessions_owner_user_id"), table_name="timer_sessions")
    op.drop_index(
        op.f("ix_timer_sessions_controller_device_id"), table_name="timer_sessions"
    )
    op.drop_index(
        op.f("ix_timer_sessions_completed_event_id"), table_name="timer_sessions"
    )
    op.drop_index(
        op.f("ix_timer_sessions_activity_node_id"), table_name="timer_sessions"
    )
    op.drop_table("timer_sessions")
    op.drop_index(
        op.f("ix_duration_day_allocations_local_date"),
        table_name="duration_day_allocations",
    )
    op.drop_index(
        op.f("ix_duration_day_allocations_activity_event_id"),
        table_name="duration_day_allocations",
    )
    op.drop_table("duration_day_allocations")
    op.drop_index(
        "uq_activity_metric_link_active_pair",
        table_name="activity_metric_links_v2",
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_activity_metric_links_v2_public_id"),
        table_name="activity_metric_links_v2",
    )
    op.drop_index(
        op.f("ix_activity_metric_links_v2_owner_user_id"),
        table_name="activity_metric_links_v2",
    )
    op.drop_index(
        op.f("ix_activity_metric_links_v2_metric_id"),
        table_name="activity_metric_links_v2",
    )
    op.drop_index(
        op.f("ix_activity_metric_links_v2_deleted_at"),
        table_name="activity_metric_links_v2",
    )
    op.drop_index(
        op.f("ix_activity_metric_links_v2_activity_node_id"),
        table_name="activity_metric_links_v2",
    )
    op.drop_table("activity_metric_links_v2")
    op.drop_index(
        "uq_activity_event_revert_target",
        table_name="activity_events",
        sqlite_where=sa.text("reverts_event_id IS NOT NULL"),
        postgresql_where=sa.text("reverts_event_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_activity_events_source_device_public_id"), table_name="activity_events"
    )
    op.drop_index(
        op.f("ix_activity_events_reverts_event_id"), table_name="activity_events"
    )
    op.drop_index(
        op.f("ix_activity_events_recorded_by_user_id"), table_name="activity_events"
    )
    op.drop_index(op.f("ix_activity_events_public_id"), table_name="activity_events")
    op.drop_index(
        op.f("ix_activity_events_owner_user_id"), table_name="activity_events"
    )
    op.drop_index(op.f("ix_activity_events_occurred_at"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_local_date"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_event_type"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_deleted_at"), table_name="activity_events")
    op.drop_index(
        op.f("ix_activity_events_activity_node_id"), table_name="activity_events"
    )
    op.drop_table("activity_events")
    op.drop_index(
        op.f("ix_user_sync_policies_primary_editor_device_id"),
        table_name="user_sync_policies",
    )
    op.drop_table("user_sync_policies")
    op.drop_index(op.f("ix_timer_commands_user_id"), table_name="timer_commands")
    op.drop_index(op.f("ix_timer_commands_status"), table_name="timer_commands")
    op.drop_index(
        op.f("ix_timer_commands_session_public_id"), table_name="timer_commands"
    )
    op.drop_index(op.f("ix_timer_commands_device_id"), table_name="timer_commands")
    op.drop_index(
        op.f("ix_timer_commands_command_sequence"), table_name="timer_commands"
    )
    op.drop_index(op.f("ix_timer_commands_command_id"), table_name="timer_commands")
    op.drop_table("timer_commands")
    op.drop_index(op.f("ix_sync_operations_user_id"), table_name="sync_operations")
    op.drop_index(op.f("ix_sync_operations_status"), table_name="sync_operations")
    op.drop_index(op.f("ix_sync_operations_operation_id"), table_name="sync_operations")
    op.drop_index(op.f("ix_sync_operations_entity_uuid"), table_name="sync_operations")
    op.drop_index(op.f("ix_sync_operations_device_id"), table_name="sync_operations")
    op.drop_table("sync_operations")
    op.drop_index(op.f("ix_sync_cursors_user_id"), table_name="sync_cursors")
    op.drop_index(op.f("ix_sync_cursors_device_id"), table_name="sync_cursors")
    op.drop_table("sync_cursors")
    op.drop_index(op.f("ix_sync_changes_recipient_user_id"), table_name="sync_changes")
    op.drop_index("ix_sync_changes_recipient_sequence", table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_origin_user_id"), table_name="sync_changes")
    op.drop_index(
        op.f("ix_sync_changes_origin_operation_id"), table_name="sync_changes"
    )
    op.drop_index(op.f("ix_sync_changes_origin_device_id"), table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_entity_uuid"), table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_entity_type"), table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_changed_at"), table_name="sync_changes")
    op.drop_table("sync_changes")
    op.drop_index(
        op.f("ix_metric_observations_source_device_public_id"),
        table_name="metric_observations",
    )
    op.drop_index(
        op.f("ix_metric_observations_recorded_by_user_id"),
        table_name="metric_observations",
    )
    op.drop_index(
        op.f("ix_metric_observations_public_id"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_owner_user_id"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_occurred_at"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_metric_id"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_local_date"), table_name="metric_observations"
    )
    op.drop_index(
        op.f("ix_metric_observations_deleted_at"), table_name="metric_observations"
    )
    op.drop_table("metric_observations")
    op.drop_index(
        op.f("ix_household_memberships_user_id"), table_name="household_memberships"
    )
    op.drop_index(
        op.f("ix_household_memberships_public_id"), table_name="household_memberships"
    )
    op.drop_index(
        op.f("ix_household_memberships_household_id"),
        table_name="household_memberships",
    )
    op.drop_index(
        op.f("ix_household_memberships_deleted_at"), table_name="household_memberships"
    )
    op.drop_table("household_memberships")
    op.drop_table("goal_details")
    op.drop_index(
        op.f("ix_entity_revision_snapshots_owner_user_id"),
        table_name="entity_revision_snapshots",
    )
    op.drop_index(
        op.f("ix_entity_revision_snapshots_origin_operation_id"),
        table_name="entity_revision_snapshots",
    )
    op.drop_index(
        op.f("ix_entity_revision_snapshots_origin_device_id"),
        table_name="entity_revision_snapshots",
    )
    op.drop_index(
        op.f("ix_entity_revision_snapshots_entity_uuid"),
        table_name="entity_revision_snapshots",
    )
    op.drop_index(
        op.f("ix_entity_revision_snapshots_entity_type"),
        table_name="entity_revision_snapshots",
    )
    op.drop_index(
        op.f("ix_entity_revision_snapshots_created_at"),
        table_name="entity_revision_snapshots",
    )
    op.drop_table("entity_revision_snapshots")
    op.drop_index(
        op.f("ix_activity_details_origin_assignment_id"), table_name="activity_details"
    )
    op.drop_table("activity_details")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_tracked_metrics_status"), table_name="tracked_metrics")
    op.drop_index(op.f("ix_tracked_metrics_public_id"), table_name="tracked_metrics")
    op.drop_index(
        op.f("ix_tracked_metrics_owner_user_id"), table_name="tracked_metrics"
    )
    op.drop_index(op.f("ix_tracked_metrics_deleted_at"), table_name="tracked_metrics")
    op.drop_index(
        op.f("ix_tracked_metrics_created_by_user_id"), table_name="tracked_metrics"
    )
    op.drop_table("tracked_metrics")
    op.drop_index(op.f("ix_plan_nodes_status"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_public_id"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_parent_node_id"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_owner_user_id"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_node_kind"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_deleted_at"), table_name="plan_nodes")
    op.drop_index(op.f("ix_plan_nodes_created_by_user_id"), table_name="plan_nodes")
    op.drop_table("plan_nodes")
    op.drop_index(op.f("ix_households_public_id"), table_name="households")
    op.drop_index(op.f("ix_households_deleted_at"), table_name="households")
    op.drop_index(op.f("ix_households_created_by_user_id"), table_name="households")
    op.drop_table("households")
    op.drop_index(op.f("ix_client_devices_user_id"), table_name="client_devices")
    op.drop_index(op.f("ix_client_devices_revoked_at"), table_name="client_devices")
    op.drop_index(op.f("ix_client_devices_public_id"), table_name="client_devices")
    op.drop_index(
        op.f("ix_client_devices_installation_id"), table_name="client_devices"
    )
    op.drop_index(op.f("ix_client_devices_device_class"), table_name="client_devices")
    op.drop_table("client_devices")
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_token_hash"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_public_id"), table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("server_instances")
    # ### end Alembic commands ###
